--liquibase formatted sql

-- changeset k.zhansaya:1
CREATE TABLE IF NOT EXISTS ROLES
(
    ID BIGSERIAL PRIMARY KEY NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
);

--changeset k.zhansaya:2
INSERT INTO ROLES(NAME)
VALUES ('ROLE_ADMIN'),
       ('ROLE_USER'),
       ('ROLE_ORGANIZER')